### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by martuuamengual** [znti/react-language-kit#4]
Hi, how are you, one question, if i dont want to use hooks because i have a component inside the class React.Component, i can make it?, how? thanks.

**Comment by znti** [comment]
Hello! As long as you are using React version 16.8.0 or above, you can use this inside class components as well.

Take a look at the code at https://github.com/znti/react-language-kit/blob/master/src/pages/Retrocompat/V120/ClassComponent.jsx
Its a Class Component using the hook inside its lifecycle.

**Comment by martudev** [comment]
Thankss!, only one question more, you have a merge with redux?

**Comment by znti** [comment]
Not currently. I believe it can be integrated with not much hassle in the reducers.

Feel free to send a PR in case you ever come around to using this arrangement and want to add it as a sample code!

**Comment by martudev** [comment]
Thanks, i need some more features so i make my own library to make more easy work. Thanks a lot really. If you want to see it here is https://github.com/martuuamengual/-react-lang-language
